### PR TITLE
fix CMakeLists not finding Qt and breaking compatibility with Qt5

### PR DESCRIPTION
**Pull request by Plaristote**
This library doesn't build with CMake, due to the lack of an instruction to look for and pick a Qt major version.

It is also advertised as being Qt5 compatible, but the `qt_add_library` command was introduced with Qt6. I don't know of a case in which such a Qt library wouldn't successfully build with CMake's own built-in command `add_library`, so I used it instead.

### CODE REVIEW

**Comment by attila-tokes** [comment]
Thanks for PR, but Qt5 is end-of-life, so I'm removing support for it.

**Comment by Plaristote** [comment]
Alright. But the CMakeLists still doesn't work, even for Qt6. Should I make another PR to fix it just for Qt6 ?

**Comment by attila-tokes** [comment]
I think, you need to provide the Qt6 installation directory to CMake. :slightly_smiling_face:  This two variants works for me:
```
$ cmake . -DQt6_DIR=/opt/qt/6.8.x/6.8.1/gcc_64/lib/cmake/Qt6 -DCMAKE_INSTALL_PREFIX="./release"
```
or
```
$ cmake . -DCMAKE_PREFIX_PATH=/opt/qt/6.8.x/6.8.1/gcc_64/lib/cmake/Qt6  -DCMAKE_INSTALL_PREFIX="./release"
```

Then:
```
$ cmake --build ./
$ cmake --install ./
```

PS: I also added these instructions to the `README` file.

**Comment by Plaristote** [comment]
It's always an option, but I don't believe it should be mandatory. The adequate `find_package` calls will allow CMake to find a suitable installation of Qt from your system, if one is available, without the user having to specify any extra options.

Unless people want to use a custom Qt installation, or a custom install directory, they shouldn't have to add any option. A typical project should build with CMake using nothing more than `cmake . && make` (and we usually use a separate build directory, as CMake is going to create a lot of files and subdirectories, and we probably want the build to be easy to clear up quickly).

Typically, you also want CMake to handle the building of all your project in one go, including tests and demos. These are typically enabled by default. People who don't want to build the test and demos along with the main target will check for options defined using cmake's `option` built-in command, which is typically useful to keep things simple and streamlined for most cases, all while letting people build without test and demos when they're in an environment that doesn't provide all the dependencies to build these targets - which is the case here, as one of the demo links to QtWidget.

It is the most common way of implementing CMake, and that's likely what people will expect to find.

You may check my latest commit to see what that would look like:
https://github.com/Plaristote/SmtpClient-for-Qt/commit/e4ca2906509da5cd0e2e54122ba2360976fac86b

**Comment by attila-tokes** [comment]
Hi @Plaristote! :slightly_smiling_face: Thanks for the refactor. I picked up your changes (commit https://github.com/bluetiger9/SmtpClient-for-Qt/commit/3268ae342ab8b96c3e99c31d1e9f246950e07a89), but left only Qt6 as supported.

**Pull request closed without merging**
