### PR TITLE
CMakeLists.txt added. SMTPEmail.pc.in added. SMTPEmail.pro updated. F…

### PR DESCRIPTION
**Pull request by SzykCech4**
…ile structure changed (headers move into Include dir, src renamed in to Src

Main inspiration to create this branch is switch my projects from qmake to cmake build system. I created CMakeLists.txt file similar to the one in https://github.com/iamantony/qtcsv project. In order to better system integration I exclude *.h files to separate subfolder: Include/ . I also renamed src/ to Src/ because I feel it is nicer to read directories and files begin with upper letter. I also added SMTPEmail.pc.in template file - this allow to use this library not only in Cmake projects, but also in Make and Autotools projects. In addition cmake generates important files which describe how to use this library (SMTPEmailConfig.cmake  SMTPEmailConfig-debug.cmake  SMTPEmailConfig-release.cmake  SMTPEmailConfigVersion.cmake). It is good move to switch now to the cmake because qmake will be dropped with Qt6 and cmake is far more complex and powerful, many projects are already build by cmake (notable Kde). I also update qmake to handle new source structure. I do basic test (compile and linking to the app, run app). But I do not make Qt4 integration test.

### CODE REVIEW

**Comment by SzykCech4** [comment]
I add made CMakeLists.txt installation multiarch like Qt and Kde.

**Comment by petem24** [comment]
Thank you very much for this!

**Comment by SzykCech4** [comment]
You have slower response than abacus...

**Comment by petem24** [comment]
The implants have been slowing me down...

**Comment by SzykCech4** [comment]
How ever it seems to fight human against machine (implant) - I don't give up! I strugle be smart and efective and coding from morning to night despite implants (and other dificulties). One day I will remove most annoying implants from my body (by medical procedure - unsure about this term from online translator). This day will be worht to celebrate in every aniversary (contradictory to my tomorrow birthday).

**Comment by SzykCech4** [comment]
@petem24:
I mistake you with SmtpClient-for-Qt project owner: "Attila Tőkés bluetiger9" - sorry for that...

**Comment by bluetiger9** [comment]
The `v1.1` version of the library is no longer in active development. However, I may switch the latest `v2.0` version of the library to cmake at some point. Thanks!

**Pull request closed without merging**
